version: 2.0

jobs:
  build:
    docker:
      - image: jivoxhub/maven:jdk8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn package
